name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout lndocs
        uses: actions/checkout@v3
        with:
          repository: laminlabs/lndocs
          ssh-key: ${{ secrets.READ_LNDOCS }}
          path: lndocs
          ref: main
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: ".github/workflows/build.yml"
      - name: cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -U laminci
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      # - run: nox -s lint
      - run: nox -s install
      - run: nox -s pull_artifacts
      - run: nox -s docs
      - name: Read lamin-project.yaml
        id: lamin-project
        uses: CumulusDS/get-yaml-paths-action@v0.1.0
        with:
          file: lamin-project.yaml
          project_slug: project_slug
      - name: Change base URL to project-slug
        if: github.event_name == 'push'
        run: |
          mv _build/html _build/html_tmp
          mkdir _build/html
          mv _build/html_tmp _build/html/${{ steps.lamin-project.outputs.project_slug }}
      - name: Deploy docs
        id: netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: "_build/html"
          production-deploy: ${{ github.event_name == 'push' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
